name: Run Pytest with Coverage + Coveralls

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start all services with environment variables
        run: |
          docker compose -f docker-compose.yaml up -d --build

      - name: Run tests and upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: pass
          CLUSTER_URL: mongodb
          ME_CONFIG_MONGODB_ADMINUSERNAME: user
          ME_CONFIG_MONGODB_ADMINPASSWORD: pass
          ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongodb/
          ME_CONFIG_BASICAUTH: false
        run: |
          docker compose run --rm api bash -c "
            pip install coveralls &&
            pytest --cov=. --cov-report=xml &&
            coveralls --service=github
          "

      - name: Shut down services
        if: always()
        run: docker compose down
