name: Run Pytest with Coverage + Coveralls

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Add deadsnakes PPA for Python 3.9
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update

      - name: Install Python 3.9.7
        run: |
          sudo apt-get install -y python3.9 python3.9-distutils python3.9-dev
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
          curl https://bootstrap.pypa.io/pip/3.9/get-pip.py -o get-pip.py
          python3.9 get-pip.py

      - name: Verify Python version
        run: python3.9 --version

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: "6.0"
          mongodb-username: user
          mongodb-password: pass

      - name: Create .env file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME=user" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=pass" >> .env
          echo "CLUSTER_URL=127.0.0.1" >> .env

      - name: Create application.yml
        run: |
          echo "GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}" >> ./backend/application.yml
          echo "GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./backend/application.yml
          echo "CONF_URL: ${{ secrets.CONF_URL }}" >> ./backend/application.yml
          echo "SECRET_KEY: ${{ secrets.SECRET_KEY }}" >> ./backend/application.yml

      - name: Install dependencies
        run: |
          cd backend
          python3.9 -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
          cd backend
          python3.9 -m coverage run -m pytest
          python3.9 -m coverage report

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backend
          python3.9 -m pip install coveralls
          python3.9 -m coveralls
