name: Run Pytest with Coverage + Coveralls

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build and start all services
        run: docker compose -f docker-compose.yaml up -d --build

      - name: Wait for services to initialize
        run: sleep 30

      - name: Run tests and upload to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          docker-compose run --rm api bash -c "
            pip install coveralls &&
            pytest --cov=. --cov-report=xml &&
            coveralls --service=github
          "

      - name: Shut down services
        if: always()
        run: docker-compose down
