name: Run Pytest with Coverage + Coveralls

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.7"

      - name: Create .env file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME=user" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=pass" >> .env
          echo "CLUSTER_URL=mongodb" >> .env
          echo "ME_CONFIG_MONGODB_ADMINUSERNAME=user" >> .env
          echo "ME_CONFIG_MONGODB_ADMINPASSWORD=pass" >> .env
          echo "ME_CONFIG_MONGODB_URL=mongodb://user:pass@mongodb/" >> .env
          echo "ME_CONFIG_BASICAUTH=false" >> .env

      - name: Create application.yml
        run: |
          echo "GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}" >> ./backend/application.yml
          echo "GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./backend/application.yml
          echo "CONF_URL: ${{ secrets.CONF_URL }}" >> ./backend/application.yml
          echo "SECRET_KEY: ${{ secrets.SECRET_KEY }}" >> ./backend/application.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          pip install pytest coverage

      - name: Test with pytest
        run: |
          cd backend
          coverage run -m pytest

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: backend/coverage.xml
