name: Run Pytest with Coverage + Coveralls

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.7"
          architecture: x64

      - name: Verify Python version
        run: python --version

      - name: Install MongoDB
        run: |
          choco install mongodb --version=6.0.5 --yes
          $env:Path += ";C:\Program Files\MongoDB\Server\6.0\bin"
          mongod --version

      - name: Start MongoDB
        run: |
          New-Item -ItemType Directory -Force -Path "C:\data\db"
          Start-Process -FilePath "mongod" -ArgumentList "--dbpath C:\data\db --auth --bind_ip 127.0.0.1" -NoNewWindow
          Start-Sleep -Seconds 10
          mongo admin --eval 'db.createUser({user: "user", pwd: "pass", roles: [{role: "root", db: "admin"}]})'

      - name: Create .env file
        run: |
          echo "MONGO_INITDB_ROOT_USERNAME=user" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=pass" >> .env
          echo "CLUSTER_URL=127.0.0.1" >> .env

      - name: Create application.yml
        run: |
          echo "GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}" >> backend\application.yml
          echo "GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}" >> backend\application.yml
          echo "CONF_URL: ${{ secrets.CONF_URL }}" >> backend\application.yml
          echo "SECRET_KEY: ${{ secrets.SECRET_KEY }}" >> backend\application.yml

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
          cd backend
          python -m coverage run -m pytest
          python -m coverage report

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backend
          python -m pip install coveralls
          python -m coveralls
